[workspace]
members = ["qemu-plugin-ready"]
resolver = "3"

[package]
name = "qemu-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.98", default-features = false, features = ["std"] }
nix = { version = "0.29.0", default-features = false, features = [
  "fs",
  "poll",
  "signal",
  "term",
] }
signal-hook = { version = "0.3.17", default-features = false, features = [
  "iterator",
] }

[dev-dependencies]
scopeguard = { version = "1.2.0", default-features = false, features = [
  "use_std",
] }
serde = { version = "1.0.219", default-features = false, features = [
  "derive",
  "std",
] }
test-binary = { version = "3.0.2", default-features = false }
toml = { version = "0.8.22", default-features = false, features = ["parse"] }
which = { version = "7.0.3", default-features = false }

[patch.crates-io]
# FIXME: remove once merged and released:
# https://gitlab.com/rust-test-binary/test-binary/-/merge_requests/24
test-binary = { git = "https://gitlab.com/davidv123/test-binary.git" }
