[target.'cfg(target_os = "macos")']
rustflags = ["-Clink-args=-undefined dynamic_lookup"]

[target.'cfg(all(target_family = "unix", not(target_os = "macos")))']
rustflags = ["-Clink-arg=-Wl,-z,undefs"]
