[target.'cfg(target_os = "macos")']
rustflags = ["-Clink-arg=-undefined", "-Clink-arg=dynamic_lookup"]

[target.'cfg(all(target_family = "unix", not(target_os = "macos")))']
rustflags = ["-C", "link-args=-Wl,-z,undefs"]
