#!/bin/sh

set -e
set -u

cargo build

ESP_DIR='esp'
BOOT_DIR="${ESP_DIR}/efi/boot"
mkdir -p "${BOOT_DIR}"

ln -f target/x86_64-unknown-uefi/debug/orderly.efi "${BOOT_DIR}/bootx64.efi"

OVMF_DIR="$(dirname "$(which qemu-system-x86_64)")/../share/qemu"
exec qemu-system-x86_64 \
	-drive if=pflash,format=raw,readonly=on,file="${OVMF_DIR}/edk2-x86_64-code.fd" \
	-drive if=pflash,format=raw,readonly=on,file="${OVMF_DIR}/edk2-i386-vars.fd" \
	-drive format=raw,file=fat:rw:"${ESP_DIR}" \
	-device isa-debug-exit,iobase=0xf4,iosize=0x01 \
	-nic none \
	-nographic \
	-no-reboot
